#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define BUILTIN_LED_GPIO        GPIO_NUM_38
#define BUILTIN_LED_POWER_PIN   GPIO_NUM_39
#define BOOT_BUTTON_GPIO        GPIO_NUM_21  // Main button

// I2C (ES8311 codec)
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_5
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_6

// I2S audio
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_11
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_9
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_12
#define AUDIO_CODEC_PA_PIN  GPIO_NUM_4

// Display - GC9107 128x128 SPI
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  128
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_13
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

#define DISPLAY_SPI_SDA_PIN  GPIO_NUM_16
#define DISPLAY_SPI_SCL_PIN  GPIO_NUM_15
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_14
#define DISPLAY_SPI_DC_PIN   GPIO_NUM_18
#define DISPLAY_SPI_RST_PIN  GPIO_NUM_17

#endif // _BOARD_CONFIG_H_
