#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_0

// I2C bus (PMIC, IO expander)
#define I2C_SDA_PIN GPIO_NUM_15
#define I2C_SCL_PIN GPIO_NUM_14

// Display - SH8601 QSPI AMOLED
#define DISPLAY_QSPI_CS    GPIO_NUM_12
#define DISPLAY_QSPI_SCLK  GPIO_NUM_11
#define DISPLAY_QSPI_DATA0 GPIO_NUM_4
#define DISPLAY_QSPI_DATA1 GPIO_NUM_5
#define DISPLAY_QSPI_DATA2 GPIO_NUM_6
#define DISPLAY_QSPI_DATA3 GPIO_NUM_7

#define DISPLAY_WIDTH   368
#define DISPLAY_HEIGHT  448
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

// TCA9554 IO expander address
#define IO_EXPANDER_I2C_ADDR 0x20

// I2S audio (ES8311 codec, shares I2C bus)
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_16
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_9
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8
#define AUDIO_CODEC_PA_PIN  GPIO_NUM_46

#endif // _BOARD_CONFIG_H_
