#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_4  // Middle button (active high)

// I2C (ES8311 codec)
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_11
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_12

// I2S audio (ES8311, no MCLK, no PA)
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_NC
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_10
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_9
#define AUDIO_CODEC_PA_PIN  GPIO_NUM_NC

// Display - ST7789 240x240 SPI
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_SPI_SCLK_PIN GPIO_NUM_39
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_40
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_41
#define DISPLAY_SPI_DC_PIN   GPIO_NUM_38
#define DISPLAY_SPI_RESET_PIN GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_
